---

  - name: Test compose
    connection: ssh
    gather_facts: False
    hosts: all
    tasks:
      - name: Copy code to remote hosts
        copy:
          src: ./code
          dest: /
          mode: 0770
          group: docker

      - name: Set dir permissions that are missed by copy
        file:
          dest: /code
          recurse: yes
          mode: 0770
          group: docker

      - name: Basic compose up
        command:
          chdir: /code
          cmd: docker-compose up -d

      - name: Wait until URL is reachable from this host
        uri:
          url: "http://{{ inventory_hostname }}"
          follow_redirects: none
          method: GET
        register: _result
        until: _result.status == 200
        retries: 24 # 24 * 5 seconds = 2 minutes
        delay: 5 # Every 5 seconds
